### ISSUE TITLE
Add gravity

### ISSUE THREAD

**Issue by ClementBeal** [Luckey-Elijah/falling_sand#10]
It's sand so it could have an option to activate gravity.

The algo would be simple.  Let's say this thing is 2 rows with a sand in the pixel
```
XXX
XSX
```
Good. Now we put another sand on it.
```
XSX
XSX
```
In this case, we have 2 empty pixel on the left and on the right. It can fall. By default, it will fall to the left.

The algorithm would be :

```python
if the pixel below is full
   if pixel[x-1][y] and pixel[x-1][y+1] == null:
       move to the left -> pixel[x-1][y] == pixel[x][y]; pixel[x][y] = null
   else if pixel[x+1][y] and pixel[x+1][y+1] == null:
       move to the left -> pixel[x+1][y] == pixel[x][y]; pixel[x][y] = null
```

**Comment by Luckey-Elijah** [comment]
We'll need to check boundaries as well, but that looks correct to me.

> By default, it will fall to the left. 
Can we chose a random side in rather than default to the left?

Also I want to keep the option to toggle this behavior. But we can have it on by default.

**Comment by Luckey-Elijah** [comment]
closing since it's pretty much done with #11
